spark {
  settings {
    appName = "SparkScalaScaffold"
    master = "local[*]"
    executorMemory = "2g"
    driverMemory = "2g"
    shufflePartitions = "200"
  }
}

dev {
  include "default"
  spark.settings {
    executorMemory = "4g"
    driverMemory = "4g"
  }
}

prod {
  include "default"
  spark.settings {
    executorMemory = "8g"
    driverMemory = "8g"
    shufflePartitions = "400"
  }
}